plugins {
    id 'java'
    id 'application'
}

group = 'io.kite'
version = '0.1.0'

repositories {
    mavenCentral()
}

def lombok = '1.18.42'

dependencies {
    // TODO: Re-enable once engine compilation issues are resolved
    // implementation project(':engine')

    implementation 'org.apache.logging.log4j:log4j-api:2.25.2'
    implementation 'org.apache.logging.log4j:log4j-core:2.25.2'
    implementation 'info.picocli:picocli:4.7.7'

    testImplementation 'org.slf4j:slf4j-jdk14:2.0.16'
    compileOnly "org.projectlombok:lombok:${lombok}"
    annotationProcessor "org.projectlombok:lombok:${lombok}"
    annotationProcessor 'info.picocli:picocli-codegen:4.7.7'
    testCompileOnly "org.projectlombok:lombok:${lombok}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombok}"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

application {
    mainClass = 'cloud.kitelang.cli.KiteCLI'
    applicationName = 'kite'
}

jar {
    archiveBaseName = "kite-cli"
}

test {
    useJUnitPlatform()
}

