package cloud.kitelang.cli.commands;

import lombok.extern.slf4j.Slf4j;
import picocli.AutoComplete;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

import java.util.concurrent.Callable;

/**
 * Generates shell completion scripts for bash, zsh, and fish.
 * Picocli provides built-in support for generating these scripts.
 */
@Command(
    name = "completion",
    description = {
        "Generate shell completion scripts",
        "",
        "Generates auto-completion scripts for your shell. Supported shells:",
        "  bash   - Bourne Again Shell",
        "  zsh    - Z Shell",
        "  fish   - Friendly Interactive Shell"
    },
    footer = {
        "",
        "Examples:",
        "  # Bash (user installation)",
        "  kite completion bash > ~/.local/share/bash-completion/completions/kite",
        "",
        "  # Bash (system-wide)",
        "  kite completion bash | sudo tee /etc/bash-completion.d/kite",
        "",
        "  # Zsh (add ~/.zfunc to fpath in .zshrc)",
        "  kite completion zsh > ~/.zfunc/_kite",
        "",
        "  # Fish",
        "  kite completion fish > ~/.config/fish/completions/kite.fish",
        "",
        "After installation, restart your shell or run: source ~/.bashrc"
    },
    mixinStandardHelpOptions = true
)
@Slf4j
public class CompletionCommand implements Callable<Integer> {

    @Parameters(
        index = "0",
        description = "Shell type: bash, zsh, or fish",
        arity = "1"
    )
    private String shell;

    @Option(
        names = {"-n", "--name"},
        description = "Name of the command (default: kite)",
        defaultValue = "kite"
    )
    private String commandName;

    @CommandLine.ParentCommand
    private Object parent;

    @Override
    public Integer call() {
        try {
            var rootCommand = findRootCommand();

            return switch (shell.toLowerCase()) {
                case "bash" -> generateBashCompletion(rootCommand);
                case "zsh" -> generateZshCompletion(rootCommand);
                case "fish" -> generateFishCompletion(rootCommand);
                default -> {
                    System.err.println("Unknown shell: " + shell);
                    System.err.println("Supported shells: bash, zsh, fish");
                    yield 1;
                }
            };
        } catch (Exception e) {
            log.error("Failed to generate completion", e);
            System.err.println("Error: " + e.getMessage());
            return 1;
        }
    }

    /**
     * Finds the root command by traversing up the parent chain.
     */
    private CommandLine findRootCommand() {
        var cmd = new CommandLine(parent);
        while (cmd.getParent() != null) {
            cmd = cmd.getParent();
        }
        return cmd;
    }

    /**
     * Generates bash completion script.
     */
    private int generateBashCompletion(CommandLine cmd) {
        var script = AutoComplete.bash(commandName, cmd);
        System.out.println(script);
        return 0;
    }

    /**
     * Generates zsh completion script.
     * Zsh can use bash completion with bashcompinit, or native zsh format.
     */
    private int generateZshCompletion(CommandLine cmd) {
        // Generate zsh completion using picocli's bash completion with zsh wrapper
        var bashScript = AutoComplete.bash(commandName, cmd);

        // Wrap in zsh compatibility
        var zshScript = """
            #compdef %s

            # Zsh completion for %s
            # Generated by kite completion zsh

            autoload -U +X bashcompinit && bashcompinit
            autoload -U +X compinit && compinit

            %s

            # vim: ft=zsh
            """.formatted(commandName, commandName, bashScript);

        System.out.println(zshScript);
        return 0;
    }

    /**
     * Generates fish completion script.
     */
    private int generateFishCompletion(CommandLine cmd) {
        // Generate fish completion
        var script = new StringBuilder();
        script.append("# Fish completion for ").append(commandName).append("\n");
        script.append("# Generated by kite completion fish\n\n");

        // Disable file completion by default
        script.append("complete -c ").append(commandName).append(" -f\n\n");

        // Add subcommand completions
        script.append("# Subcommands\n");
        for (var sub : cmd.getSubcommands().entrySet()) {
            var name = sub.getKey();
            var subCmd = sub.getValue();
            var desc = getFirstLine(subCmd.getCommandSpec().usageMessage().description());
            script.append("complete -c ").append(commandName)
                  .append(" -n \"__fish_use_subcommand\"")
                  .append(" -a ").append(name)
                  .append(" -d \"").append(escapeForFish(desc)).append("\"\n");
        }

        script.append("\n# Global options\n");
        script.append("complete -c ").append(commandName).append(" -s h -l help -d \"Show help\"\n");
        script.append("complete -c ").append(commandName).append(" -s v -l version -d \"Show version\"\n");

        // Add common options for subcommands
        script.append("\n# Common options\n");
        script.append("complete -c ").append(commandName).append(" -l env -s e -d \"Target environment\" -a \"dev staging prod\"\n");
        script.append("complete -c ").append(commandName).append(" -l provider -s p -d \"Cloud provider\" -a \"aws gcp azure all\"\n");
        script.append("complete -c ").append(commandName).append(" -l stack -s s -d \"Stack name\" -a \"Backend Frontend\"\n");

        System.out.println(script);
        return 0;
    }

    /**
     * Gets the first line of a description array.
     */
    private String getFirstLine(String[] description) {
        if (description == null || description.length == 0) {
            return "";
        }
        return description[0];
    }

    /**
     * Escapes special characters for fish shell.
     */
    private String escapeForFish(String text) {
        if (text == null) return "";
        return text.replace("\"", "\\\"").replace("$", "\\$");
    }
}
